- name: Run-stage - Run yum update and reboot
  hosts: your_target_group
  become: yes
  tasks:
    - name: Run yum update
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Reboot the system
      ansible.builtin.reboot: